# Generated by Django 5.0.1 on 2024-02-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_answer_next_question_alter_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='participants',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poll',
            name='participants',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='participants',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
