# Generated by Django 5.0.1 on 2024-02-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_answer_participants_poll_participants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_start',
            field=models.BooleanField(default=False),
        ),
    ]
